/* Remove database seeding data */
TRUNCATE TABLE sub_team CASCADE;
TRUNCATE TABLE team CASCADE;
TRUNCATE TABLE cost_center CASCADE;
TRUNCATE TABLE vendor CASCADE;
TRUNCATE TABLE designation CASCADE;
TRUNCATE TABLE location CASCADE;
TRUNCATE TABLE location_block CASCADE;
TRUNCATE TABLE seat CASCADE;
TRUNCATE TABLE employee CASCADE;
